//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "RodClient")]
public interface RodClient
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/RodClient/WriteMessage", ReplyAction = "http://tempuri.org/RodClient/WriteMessageResponse")]
    bool WriteMessage(string message);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/RodClient/WriteMessage", ReplyAction = "http://tempuri.org/RodClient/WriteMessageResponse")]
    System.Threading.Tasks.Task<bool> WriteMessageAsync(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface RodClientChannel : RodClient, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RodClientClient : System.ServiceModel.ClientBase<RodClient>, RodClient
{

    public RodClientClient()
    {
    }

    public RodClientClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public RodClientClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public RodClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public RodClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public bool WriteMessage(string message)
    {
        return base.Channel.WriteMessage(message);
    }

    public System.Threading.Tasks.Task<bool> WriteMessageAsync(string message)
    {
        return base.Channel.WriteMessageAsync(message);
    }
}
